[package]
name = "check64"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22"
chardet = "0.2"
encoding_rs = "0.8"
regex = "1.11"

[profile.release]
opt-level = "z"
lto = true       
panic = "abort"
codegen-units = 1
strip = "symbols"